spring:
  profiles:
    #环境
    active: dev
    #服务名
  application:
    name: service-dormitory
    #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/ldormitory?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 18756232770lmh
    driver-class-name: com.mysql.cj.jdbc.Driver
    #全局时间json格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #指定mapper.xml
mybatis-plus:
  mapper-locations: classpath:com/lmh/dormitoryService/mapper/xml/*.xml
  #使用logback要把下面注释掉
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#端口号
server:
  port: 8004